CCIP-4303: Setting PG instance for integration tests
smartcontractkit/.github pull request #719
Opened 2024-11-22 16:06 UTC by b-gopalswami

In order to have in-memory test in integration-tests workflow. We need PG instances. This PR is setting up the PG instance if at all requested in test matrix using this env variable PG_INSTANCE.

2024-11-22 18:38 UTC, kalverra requested changes

2024-11-22 18:38 UTC, kalverra commented on .github/workflows/run-e2e-tests.yml
> +      - name: Setup postgres
I think we should separate this out into its own workflow instead of bolting it onto the E2E tests.

2024-11-25 21:36 UTC, kalverra requested changes

2024-11-25 21:36 UTC, kalverra commented on .github/workflows/run-integration-tests.yml
> +  CHAINLINK_IMAGE:
If these are more traditional integration tests, are we still using Chainlink docker images? I assumed these would be in-memory?

2024-11-25 21:36 UTC, kalverra commented on actions/setup-postgres/docker-compose.yml
Check out [GHA service containers](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers), which should handle this sort of thing with less overhead in GHA.

2024-11-26 17:39 UTC, kalverra submitted a review, later dismissed

2024-11-26 17:41 UTC, b-gopalswami commented on .github/workflows/run-integration-tests.yml
> +        uses: smartcontractkit/.github/actions/ctf-run-tests@b8731364b119e88983e94b0c4da87fc27ddb41b8 # ctf-run-tests@0.0.0
As discussed offline, will improvise this with follow up PR.

2024-11-26 19:06 UTC, chainchad approved these changes

2024-11-26 19:40 UTC, merged