[NONEVM-641] Starting Gauntlet Plus Plus Container on CTF Run Tests Start up
smartcontractkit/.github pull request #720
Opened 2024-11-22 22:01 UTC by chray-zhang

### Description
As part of the effort to migrate the [chainlink-starknet](https://github.com/smartcontractkit/chainlink-starknet) E2E tests from legacy gauntlet to gauntlet++ we need to start an instance of Gpp on E2E test initialization. This ticket pulls the image from the Prod ECR which would allow the E2E tests to use for its container

### Changes
Added an extra action that pull the gauntlet-plus-plus image from the Prod ECR

### Ticket
[NONEVM-641](https://smartcontract-it.atlassian.net/browse/NONEVM-641)

2024-11-27 15:35 UTC, kalverra approved these changes

2025-03-20 18:30 UTC, jmank88 approved these changes

2025-03-20 19:46 UTC, erikburt requested changes

2025-03-20 19:46 UTC, erikburt commented on actions/ctf-setup-gauntlet-plus-plus/README.md
Can you populate this at least a little bit?

2025-03-20 20:38 UTC, chray-zhang commented on actions/ctf-setup-gauntlet-plus-plus/action.yml
> +    required: false
Resolved in: https://github.com/smartcontractkit/.github/pull/948/files

2025-03-20 20:39 UTC, chray-zhang commented on actions/ctf-run-tests/action.yml
> +      uses: smartcontractkit/.github/actions/ctf-setup-run-tests-environment@bf800f15fe032b9dc1230b0a041a1f179b8c2474 # ctf-setup-run-tests-environment@v0.5.1
ctf-setup-gauntlet-plus-plus PR: https://github.com/smartcontractkit/.github/pull/948/files

2025-06-06 16:48 UTC, chainchad commented
This looks to be sale. Please update it, merge it, or remove the `Stale` label or it will be closed by the bot in ~7 days.

2025-06-19 01:32 UTC, closed without merging